public with sharing class PositionHandler extends TriggerAbstract implements TriggerAbstract.MyTrigger{
    
     public PositionHandler() {




     }
      
      public void beforeInsert(SObject currentObject) {
      	
      	
      	
      	
      	
     } 
     public void afterInsert(SObject currentObject) {
     	
     	
     	
     	
     }
     
     public void beforeUpdate(SObject oldSobject, SObject currentObject) {
     	
     	
     	
     	
     	
     }
     
     public void beforeDelete(SObject currentObject) {
     	
     	
     	
     	
     	
     }
     
     
     
     public void afterUpdate(SObject oldSobject, SObject currentObject) {
     	
     	
     	
     	
     	
     	
         
     }
     
     public void afterDelete(SObject currentObject) {
     	
     	
     	
         
     }
     
     public Boolean skipExecution() {
     	
     	
     	
         return false;
         
         
     }
    
}